### ISSUE TITLE
add command - ability to add its own repository (local or not)

### ISSUE THREAD

**Issue by k33g** [mklabs/gimme-assets#10]

**Comment by mklabs** [comment]
You're looking about a way to define additional packages? 

I think that the only repository should remain github itself. But I'm not against something that let you create and define custom packages, that are not originally on cndjs / microjs (optionnaly with files that are not necessarily  .js files, eg. .css, .html, .less, or even a whole repo).

**Comment by mklabs** [comment]
c4618c6782a26a6760a5b4aa311c00aa12ee93cc
