### ISSUE TITLE
batch mode

### ISSUE THREAD

**Issue by k33g** [mklabs/gimme-assets#6]

**Comment by k33g** [comment]
i.e. : ability to create complete project structure from template script

**Comment by mklabs** [comment]
Not sure I understand what you mean.. :p

What is a "template script"? If you'd like some project scaffolding from a predefined template, then [grunt](https://github.com/cowboy/grunt)'s init is pretty cool. I'm using / playing with it a lot lately.

**Comment by k33g** [comment]
i need something to create directory (even empty)

**Comment by mklabs** [comment]
https://gist.github.com/1927612

basically, a nice api to do something like this, thx for the gist

**Comment by k33g** [comment]
yes ;)
