### ISSUE TITLE
gimme install jquery

### ISSUE THREAD

**Issue by k33g** [mklabs/gimme-assets#8]
Hello

under windows (xp) i launch `gimme install jquery`

and then : 

```
log   - Installing... jquery
error - ENOENT, no such file or directory 'D:\jsproj\.gimme\ajax\libs\jquery\1.7.1\jquery.min.js'
```

**Comment by mklabs** [comment]
Thanks again Philippe for the feedback. I'll take a look and try to reproduce rather quickly.

Also, may I ask if you're behind any proxy of some sort? gimme has some logic involved that change a lot to make it work behind corporate proxies.

**Comment by k33g** [comment]
yes, but what kind of proxy .... euh ...
i know, that doesn't help
